local: "Application locale\n(Python)" {
  gui: "Interface graphique\n(Tkinter)" {
    generate: "Génération\n(paramètres)"
    stats: "Statistiques"
    updatescore: "Modification du score"
    database: "Recherche BD"
    play: "Lancement du jeu"
    plot: "Visualisation\n(Matplotlib)"
  }

  engine: "Moteur de jeu\n(Pacman)" {
    logic: "Logique du jeu\n- règles\n- déplacements\n- collisions\n- score"
    replay: "Gestion des replays"
  }

  agents: "Agents" {
    pacman: "Agent Pac-Man"
    ghosts: "Agents Fantômes"
  }

  files: "Fichiers locaux" {
    mazes: "Labyrinthes\n(JSON)"
    records: "record.json"
  }

  cloud: "API Cloud"

  gui.generate -> cloud: "Requête HTTP"
  gui.updatescore -> cloud: "Requête HTTP"
  gui.database -> cloud: "Requête HTTP"

  cloud -> gui.plot: "JSON Labyrinthe"
  cloud -> gui.stats: "JSON Labyrinthe"

  files.mazes -> gui.plot: "JSON Labyrinthe"
  files.mazes -> gui.stats: "JSON Labyrinthe"

  gui.play -> engine: "Configuration\n+ paramètres"
  engine -> agents: "Instanciation\n& contrôle"
  engine.replay -> files.records
}
